version: '3.8'
services:
  postgres:
    image: postgres:latest
    container_name: foodorderingsystemdb
    environment:
      POSTGRES_USER: foodorderingsystem
      POSTGRES_PASSWORD: foodorderingsystem
      POSTGRES_DB: foodorderingsystemdb
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    depends_on:
      - postgres
volumes:
  postgres-data: